/* Generated By:JavaCC: Do not edit this line. testTokenManager.java */

/** Token Manager. */
public class testTokenManager implements testConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 180;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 5);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(3);
                  break;
               case 3:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 5:
                  if (curChar == 45)
                     jjCheckNAddStates(6, 8);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(9, 12);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 5);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(13, 15);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(6, 13);
                  break;
               case 13:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(5, 10);
                  break;
               case 15:
                  if (curChar == 45)
                     jjCheckNAddStates(19, 23);
                  break;
               case 16:
                  if (curChar == 45)
                     jjCheckNAdd(17);
                  break;
               case 17:
                  if (curChar == 45)
                     jjCheckNAddStates(24, 26);
                  break;
               case 18:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(20, 21);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 21:
                  if (curChar == 45)
                     jjCheckNAddStates(27, 29);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(30, 32);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(33, 35);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(22, 26);
                  break;
               case 26:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(21, 19);
                  break;
               case 28:
                  if (curChar == 45)
                     jjCheckNAddStates(36, 40);
                  break;
               case 29:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(29, 30);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 32:
                  if (curChar == 45)
                     jjCheckNAddStates(41, 43);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(44, 47);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(32);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(35, 32);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(48, 50);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(51, 53);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(33, 40);
                  break;
               case 40:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(32, 37);
                  break;
               case 42:
                  if (curChar == 45)
                     jjCheckNAddStates(54, 58);
                  break;
               case 43:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(43, 44);
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(45);
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(46);
                  break;
               case 46:
                  if (curChar == 45)
                     jjCheckNAddStates(59, 61);
                  break;
               case 48:
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(46, 45);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(62, 64);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(47, 51);
                  break;
               case 51:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(51, 52);
                  break;
               case 53:
                  if (curChar == 45)
                     jjCheckNAddStates(65, 69);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(55);
                  break;
               case 55:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(55, 56);
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(57, 58);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(58);
                  break;
               case 58:
                  if (curChar == 45)
                     jjCheckNAddStates(70, 72);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(73, 75);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(76, 78);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 63);
                  break;
               case 63:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(58, 56);
                  break;
               case 65:
                  if (curChar == 45)
                     jjCheckNAddStates(79, 83);
                  break;
               case 66:
                  if (curChar == 45)
                     jjCheckNAdd(67);
                  break;
               case 67:
                  if (curChar == 45)
                     jjCheckNAddStates(84, 86);
                  break;
               case 68:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(68, 69);
                  break;
               case 70:
                  if (curChar == 45)
                     jjCheckNAddStates(87, 89);
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(90, 93);
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(70);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(73, 70);
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(94, 96);
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(97, 99);
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(71, 78);
                  break;
               case 78:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(70, 75);
                  break;
               case 80:
                  if (curChar == 45)
                     jjCheckNAddStates(100, 104);
                  break;
               case 81:
                  if (curChar == 45)
                     jjCheckNAddStates(105, 114);
                  break;
               case 82:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(82, 83);
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(84);
                  break;
               case 84:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(84, 85);
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(86, 87);
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(87);
                  break;
               case 87:
                  if (curChar == 45)
                     jjCheckNAddStates(115, 117);
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(118, 120);
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(121, 123);
                  break;
               case 91:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(88, 92);
                  break;
               case 92:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(92, 93);
                  break;
               case 93:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(87, 85);
                  break;
               case 94:
                  if (curChar == 45)
                     jjCheckNAddStates(124, 128);
                  break;
               case 95:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(95, 96);
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(96, 98);
                  break;
               case 99:
                  if (curChar == 45)
                     jjCheckNAddStates(129, 131);
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(132, 135);
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(99);
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(102, 99);
                  break;
               case 104:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(136, 138);
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(139, 141);
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(100, 107);
                  break;
               case 107:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(107, 108);
                  break;
               case 108:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(99, 104);
                  break;
               case 109:
                  if (curChar == 45)
                     jjCheckNAddStates(142, 146);
                  break;
               case 110:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(110, 111);
                  break;
               case 111:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(112);
                  break;
               case 112:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(112, 113);
                  break;
               case 114:
                  if (curChar == 45)
                     jjCheckNAddStates(147, 149);
                  break;
               case 116:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(150, 153);
                  break;
               case 117:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(114);
                  break;
               case 118:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 114);
                  break;
               case 119:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(154, 156);
                  break;
               case 120:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(157, 159);
                  break;
               case 121:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(115, 122);
                  break;
               case 122:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(122, 123);
                  break;
               case 123:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(114, 119);
                  break;
               case 124:
                  if (curChar == 45)
                     jjCheckNAddStates(160, 164);
                  break;
               case 125:
                  if (curChar == 45)
                     jjCheckNAddStates(165, 167);
                  break;
               case 126:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(126, 127);
                  break;
               case 128:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(129, 130);
                  break;
               case 129:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(130);
                  break;
               case 130:
                  if (curChar == 45)
                     jjCheckNAddStates(168, 170);
                  break;
               case 132:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(171, 173);
                  break;
               case 133:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(174, 176);
                  break;
               case 134:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(131, 135);
                  break;
               case 135:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(135, 136);
                  break;
               case 136:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(130, 128);
                  break;
               case 137:
                  if (curChar == 45)
                     jjCheckNAddStates(177, 181);
                  break;
               case 138:
                  if (curChar == 45)
                     jjCheckNAddStates(182, 184);
                  break;
               case 139:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(139, 140);
                  break;
               case 140:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 142:
                  if (curChar == 45)
                     jjCheckNAddStates(185, 187);
                  break;
               case 144:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(188, 191);
                  break;
               case 145:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(142);
                  break;
               case 146:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(145, 142);
                  break;
               case 147:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(192, 194);
                  break;
               case 148:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(195, 197);
                  break;
               case 149:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(143, 150);
                  break;
               case 150:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(150, 151);
                  break;
               case 151:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(142, 147);
                  break;
               case 152:
                  if (curChar == 45)
                     jjCheckNAddStates(198, 202);
                  break;
               case 153:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(154, 153);
                  break;
               case 154:
                  if (curChar == 45)
                     jjCheckNAddStates(203, 205);
                  break;
               case 155:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(155, 156);
                  break;
               case 157:
                  if (curChar == 45)
                     jjCheckNAddStates(206, 208);
                  break;
               case 159:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(209, 212);
                  break;
               case 160:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(157);
                  break;
               case 161:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(160, 157);
                  break;
               case 162:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(213, 215);
                  break;
               case 163:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(216, 218);
                  break;
               case 164:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(158, 165);
                  break;
               case 165:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(165, 166);
                  break;
               case 166:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(157, 162);
                  break;
               case 167:
                  if (curChar == 45)
                     jjCheckNAddStates(219, 223);
                  break;
               case 168:
                  if (curChar == 45)
                     jjCheckNAddStates(224, 226);
                  break;
               case 169:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(169, 170);
                  break;
               case 170:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(171);
                  break;
               case 171:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(172);
                  break;
               case 172:
                  if (curChar == 45)
                     jjCheckNAddStates(227, 229);
                  break;
               case 174:
               case 178:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(172, 171);
                  break;
               case 175:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(230, 232);
                  break;
               case 176:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(173, 177);
                  break;
               case 177:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(177, 178);
                  break;
               case 179:
                  if (curChar == 45)
                     jjCheckNAddStates(233, 237);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x87fffffeL & l) != 0L)
                     jjAddStates(238, 239);
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(240, 242);
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(6, 8);
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(243, 245);
                  break;
               case 13:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 16:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAdd(17);
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(24, 26);
                  break;
               case 18:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(27, 29);
                  break;
               case 22:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(246, 248);
                  break;
               case 26:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 28:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(36, 40);
                  break;
               case 29:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(249, 250);
                  break;
               case 31:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(251, 253);
                  break;
               case 32:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 33:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(254, 256);
                  break;
               case 40:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 42:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(54, 58);
                  break;
               case 43:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(257, 258);
                  break;
               case 46:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(59, 61);
                  break;
               case 47:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(259, 261);
                  break;
               case 51:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(51, 52);
                  break;
               case 53:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(65, 69);
                  break;
               case 55:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(262, 263);
                  break;
               case 58:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(70, 72);
                  break;
               case 59:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(264, 266);
                  break;
               case 63:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 65:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(79, 83);
                  break;
               case 66:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAdd(67);
                  break;
               case 67:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(84, 86);
                  break;
               case 68:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(68, 69);
                  break;
               case 69:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(267, 269);
                  break;
               case 70:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(87, 89);
                  break;
               case 71:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(270, 272);
                  break;
               case 78:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 80:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(100, 104);
                  break;
               case 81:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(105, 114);
                  break;
               case 82:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(82, 83);
                  break;
               case 84:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(273, 274);
                  break;
               case 87:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(115, 117);
                  break;
               case 88:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(275, 277);
                  break;
               case 92:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(92, 93);
                  break;
               case 94:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(124, 128);
                  break;
               case 95:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(95, 96);
                  break;
               case 98:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(278, 280);
                  break;
               case 99:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(129, 131);
                  break;
               case 100:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(281, 283);
                  break;
               case 107:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(107, 108);
                  break;
               case 109:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(142, 146);
                  break;
               case 110:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(110, 111);
                  break;
               case 112:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(112, 113);
                  break;
               case 113:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(284, 286);
                  break;
               case 114:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(147, 149);
                  break;
               case 115:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(287, 289);
                  break;
               case 122:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(122, 123);
                  break;
               case 124:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(160, 164);
                  break;
               case 125:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(165, 167);
                  break;
               case 126:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(126, 127);
                  break;
               case 127:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(127, 128);
                  break;
               case 130:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(168, 170);
                  break;
               case 131:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(290, 292);
                  break;
               case 135:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(135, 136);
                  break;
               case 137:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(177, 181);
                  break;
               case 138:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(182, 184);
                  break;
               case 139:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(139, 140);
                  break;
               case 141:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(293, 295);
                  break;
               case 142:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(185, 187);
                  break;
               case 143:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(296, 298);
                  break;
               case 150:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(150, 151);
                  break;
               case 152:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(198, 202);
                  break;
               case 153:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(154, 153);
                  break;
               case 154:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(203, 205);
                  break;
               case 155:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(155, 156);
                  break;
               case 156:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(299, 301);
                  break;
               case 157:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(206, 208);
                  break;
               case 158:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(302, 304);
                  break;
               case 165:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(165, 166);
                  break;
               case 167:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(219, 223);
                  break;
               case 168:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(224, 226);
                  break;
               case 169:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(169, 170);
                  break;
               case 172:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(227, 229);
                  break;
               case 173:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(305, 307);
                  break;
               case 177:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(177, 178);
                  break;
               case 179:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(233, 237);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 180 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   2, 16, 29, 43, 54, 66, 6, 11, 15, 8, 5, 9, 10, 8, 5, 9, 
   12, 6, 13, 6, 13, 14, 11, 15, 18, 19, 17, 22, 24, 28, 20, 21, 
   19, 25, 22, 26, 22, 26, 27, 24, 28, 33, 38, 42, 35, 32, 36, 37, 
   35, 32, 36, 39, 33, 40, 33, 40, 41, 38, 42, 47, 49, 53, 50, 47, 
   51, 47, 51, 52, 49, 53, 59, 61, 65, 57, 58, 56, 62, 59, 63, 59, 
   63, 64, 61, 65, 68, 69, 67, 71, 76, 80, 73, 70, 74, 75, 73, 70, 
   74, 77, 71, 78, 71, 78, 79, 76, 80, 82, 83, 95, 96, 110, 111, 125, 
   138, 153, 168, 88, 90, 94, 86, 87, 85, 91, 88, 92, 88, 92, 93, 90, 
   94, 100, 105, 109, 102, 99, 103, 104, 102, 99, 103, 106, 100, 107, 100, 107, 
   108, 105, 109, 115, 120, 124, 117, 114, 118, 119, 117, 114, 118, 121, 115, 122, 
   115, 122, 123, 120, 124, 126, 127, 125, 131, 133, 137, 129, 130, 128, 134, 131, 
   135, 131, 135, 136, 133, 137, 139, 140, 138, 143, 148, 152, 145, 142, 146, 147, 
   145, 142, 146, 149, 143, 150, 143, 150, 151, 148, 152, 155, 156, 154, 158, 163, 
   167, 160, 157, 161, 162, 160, 157, 161, 164, 158, 165, 158, 165, 166, 163, 167, 
   169, 170, 168, 173, 175, 179, 176, 173, 177, 173, 177, 178, 175, 179, 1, 81, 
   4, 5, 9, 5, 6, 7, 21, 22, 23, 29, 30, 31, 32, 36, 32, 33, 
   34, 43, 44, 46, 47, 48, 55, 56, 58, 59, 60, 69, 70, 74, 70, 71, 
   72, 84, 85, 87, 88, 89, 98, 99, 103, 99, 100, 101, 113, 114, 118, 114, 
   115, 116, 130, 131, 132, 141, 142, 146, 142, 143, 144, 156, 157, 161, 157, 158, 
   159, 172, 173, 174, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x801L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[180];
static private final int[] jjstateSet = new int[360];
static protected char curChar;
/** Constructor. */
public testTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public testTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 180; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
